version: '3.8'
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    restart: always
    networks:
      - mongoCluster
    ports:
      - 27017:27017
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    volumes: 
      - ./dbSaves/mongo1:/data/db

  mongo2:
    container_name: mongo2
    image: mongo:latest
    restart: always
    networks:
      - mongoCluster
    ports:
      - 27018:27017
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    volumes: 
      - ./dbSaves/mongo2:/data/db

  mongo3:
    container_name: mongo3
    image: mongo:latest
    restart: always
    networks:
      - mongoCluster
    ports:
      - 27019:27017
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    volumes: 
      - ./dbSaves/mongo3:/data/db
  
  nodejs:
    container_name: nodejs
    image: node:latest
    networks:
      - mongoCluster
    ports:
      - 3000:3000
    volumes:
    - ./scripts:/app
    command: ["tail", "-f", "/dev/null"]

networks:
  mongoCluster:
    name: mongoCluster