version: "3.8"

services:
  mongo1:
    image: mongo:latest
    container_name: MongoDB_Container
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - "mongo1_data:/data/db"

volumes:
  mongo1_data:
