version: "3.8"

services:
  mongo1:
    image: mongo:latest
    restart: always
    container_name: MongoDB_Container
    command: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - "mongo1_data:/data/db"

volumes:
  mongo1_data: